#Sky Archipelago + Terralith + Cataclysm compat
#Sun May 17 12:49:50 MSK 2026
enableCataclysmStructureHosts=true
enableForcedStructureIslands=true
enableTerralithStructureHosts=true
enableWaterStructureHosts=true
verboseStructureHostLogs=false
